// Canonical list of countries used as product origins across the platform.
// Single source of truth for both buyer-side filters and seller-side product forms.
export const ORIGIN_COUNTRIES: readonly string[] = [
  "Afghanistan",
  "Angola",
  "Argentina",
  "Armenia",
  "Australia",
  "Azerbaijan",
  "Brazil",
  "Bulgaria",
  "Cambodia",
  "Chile",
  "China",
  "Colombia",
  "Costa Rica",
  "Côte d’Ivoire",
  "Czech Republic",
  "Dominican Republic",
  "Egypt",
  "Ethiopia",
  "France",
  "Georgia",
  "Germany",
  "Greece",
  "Hungary",
  "India",
  "Indonesia",
  "Iran",
  "Italy",
  "Kazakhstan",
  "Kenya",
  "Laos",
  "Malaysia",
  "Mexico",
  "Morocco",
  "Myanmar",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Pakistan",
  "Panama",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Romania",
  "Saudi Arabia",
  "South Africa",
  "Spain",
  "Sudan",
  "Tanzania",
  "Thailand",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United States",
  "Uzbekistan",
  "Vietnam",
] as const;
